### ISSUE TITLE
Pretrained model release

### ISSUE THREAD

**Issue by Zxl19990529** [Luffy03/AGMM-SASS#1]
Hi, thanks for your work.
I entounter the miss matching problem when using the pretrained resnet101 model. 
<details><summary>Details</summary>
<p>

Traceback (most recent call last):
  File "train_voc.py", line 160, in <module>
    main()
  File "train_voc.py", line 51, in main
    model = DeepLabV3Plus(cfg, aux=cfg['aux'])
  File "/home/zxl/AGMM-SASS-main/model/semseg/deeplabv3plus.py", line 12, in __init__
    resnet.__dict__[cfg['backbone']](True, multi_grid=cfg['multi_grid'],
  File "/home/zxl/AGMM-SASS-main/model/backbone/resnet.py", line 169, in resnet101
    return _resnet('resnet101', Bottleneck, [3, 4, 23, 3], pretrained, **kwargs)
  File "/home/zxl/AGMM-SASS-main/model/backbone/resnet.py", line 159, in _resnet
    model.load_state_dict(state_dict, strict=False)
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNet:
        size mismatch for bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
        size mismatch for layer1.0.downsample.0.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24549) of binary: /home/zxl/anaconda3/envs/urss/bin/python
Traceback (most recent call last):
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zxl/anaconda3/envs/urss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_voc.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-24_14:40:02
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24549)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

</p>
</details> 
I am running with script
```bash
sh tools/train_voc.sh 1 28890
```
I download the pretrained model from offical pytorch model zone: "https://download.pytorch.org/models/resnet101-63fe2227.pth" 

Is that the problem that the code needs a different version pretrained resnet101 model? If so, can you release it?

**Comment by Luffy03** [comment]
Thanks for your kind comments!
The pre-trained model are released now. Please check.
